"""
Generates tasmiq_expert_system.ipynb
- Improved UI with auto-loading
- Audio normalization/trimming for better accuracy
- Comparison against reference phonetics (cancels engine bias)
"""
import json
from pathlib import Path

NB_PATH = Path(__file__).parent / "tasmiq_expert_system.ipynb"

def code_cell(lines):
    return {"cell_type": "code", "execution_count": None,
            "metadata": {}, "outputs": [], "source": lines}

def md_cell(lines):
    return {"cell_type": "markdown", "metadata": {}, "source": lines}

INSTALL_LINES = [
    "import sys\n",
    "!{sys.executable} -m pip install gradio soundfile librosa transformers torch --quiet\n",
    "print('✅ Done. Run Cell 2.')"
]

APP_LINES = [
    "import json, logging, traceback, os\n",
    "import numpy as np\n",
    "from pathlib import Path\n",
    "from difflib import SequenceMatcher\n",
    "import soundfile as sf\n",
    "import librosa\n",
    "import torch\n",
    "import gradio as gr\n",
    "from transformers import Wav2Vec2Processor, Wav2Vec2ForCTC\n",
    "\n",
    "logging.basicConfig(level=logging.WARNING)\n",
    "\n",
    "DATASET_ROOT = Path(r'C:\\Users\\nabil\\.gemini\\antigravity\\scratch\\quranjson\\source')\n",
    "AUDIO_ROOT   = DATASET_ROOT / 'audio'\n",
    "SURAH_DIR    = DATASET_ROOT / 'surah'\n",
    "\n",
    "print('📂 Loading Quran dataset...')\n",
    "quran = {}\n",
    "for _sf in sorted(SURAH_DIR.glob('surah_*.json'), key=lambda p: int(p.stem.split('_')[1])):\n",
    "    with open(_sf, 'r', encoding='utf-8') as _f:\n",
    "        _d = json.load(_f)\n",
    "    quran[int(_d['index'])] = _d\n",
    "print(f'✅ {len(quran)} surahs loaded.')\n",
    "\n",
    "def get_ayah(s, a): return quran.get(s,{}).get('verse',{}).get(f'verse_{a}','[not found]')\n",
    "def get_name(s): return quran.get(s,{}).get('name',f'Surah {s}')\n",
    "def get_count(s): return quran.get(s,{}).get('count',0)\n",
    "def ref_audio_p(s, a): return AUDIO_ROOT / f'{s:03d}' / f'{a:03d}.mp3'\n",
    "\n",
    "print('⏳ Loading Wav2Vec2 model...')\n",
    "_proc  = Wav2Vec2Processor.from_pretrained('TBOGamer22/wav2vec2-quran-phonetics')\n",
    "_model = Wav2Vec2ForCTC.from_pretrained('TBOGamer22/wav2vec2-quran-phonetics')\n",
    "_model.eval()\n",
    "_dev = 'cuda' if torch.cuda.is_available() else 'cpu'\n",
    "_model.to(_dev)\n",
    "print(f'✅ Model on {_dev}')\n",
    "\n",
    "def load_processed(path_or_tuple, sr=16000):\n",
    "    if isinstance(path_or_tuple, tuple): # Gradio (sr, numpy)\n",
    "        s_rate, arr = path_or_tuple\n",
    "        arr = arr.astype(np.float32)\n",
    "        if arr.ndim > 1: arr = arr.mean(axis=1)\n",
    "        if arr.max() > 1.0: arr = arr / 32768.0\n",
    "        if s_rate != sr: arr = librosa.resample(arr, orig_sr=s_rate, target_sr=sr)\n",
    "    else:\n",
    "        try:\n",
    "            arr, s_rate = sf.read(str(path_or_tuple), dtype='float32')\n",
    "            if arr.ndim > 1: arr = arr.mean(axis=1)\n",
    "            if s_rate != sr: arr = librosa.resample(arr, orig_sr=s_rate, target_sr=sr)\n",
    "        except Exception:\n",
    "            arr, _ = librosa.load(str(path_or_tuple), sr=sr, mono=True)\n",
    "    arr, _ = librosa.effects.trim(arr, top_db=20)\n",
    "    if len(arr) > 0: arr = librosa.util.normalize(arr)\n",
    "    return arr\n",
    "\n",
    "def infer_phonetic(audio_arr):\n",
    "    if len(audio_arr) == 0: return '[no audio]'\n",
    "    inp = _proc(audio_arr, sampling_rate=16000, return_tensors='pt', padding=True)\n",
    "    inp = {k: v.to(_dev) for k, v in inp.items()}\n",
    "    with torch.inference_mode():\n",
    "        logits = _model(**inp).logits\n",
    "    ids = torch.argmax(logits, dim=-1)\n",
    "    return _proc.batch_decode(ids, skip_special_tokens=True)[0].strip()\n",
    "\n",
    "def auto_load_ayah(surah_label, ayah_num):\n",
    "    try:\n",
    "        s = int(str(surah_label).split('.')[0].strip())\n",
    "        a = int(float(ayah_num))\n",
    "        arabic = get_ayah(s, a)\n",
    "        ap = ref_audio_p(s, a)\n",
    "        msg = \"✅ Ayah loaded. Listen to reference, then record below.\"\n",
    "        if not ap.exists(): msg = \"⚠️ Audio missing in dataset.\"\n",
    "        \n",
    "        ref_path = None\n",
    "        if ap.exists():\n",
    "            import shutil\n",
    "            cache_dir = Path('./ref_cache')\n",
    "            cache_dir.mkdir(exist_ok=True)\n",
    "            local_path = cache_dir / f'{s:03d}_{a:03d}.mp3'\n",
    "            if not local_path.exists():\n",
    "                shutil.copy(str(ap), str(local_path))\n",
    "            ref_path = str(local_path)\n",
    "            \n",
    "        return f'📖 Surah {s}: {get_name(s)} | Ayah {a}', arabic, ref_path, msg\n",
    "    except Exception as e:\n",
    "        return \"Error loading\", f\"Error: {e}\", None, traceback.format_exc()\n",
    "\n",
    "def run_check(surah_label, ayah_num, user_audio):\n",
    "    try:\n",
    "        if user_audio is None: return \"⚠️ Record voice first.\", \"\", \"\", \"\"\n",
    "        s = int(str(surah_label).split('.')[0].strip())\n",
    "        a = int(float(ayah_num))\n",
    "        ref_ap = ref_audio_p(s, a)\n",
    "        \n",
    "        u_arr = load_processed(user_audio)\n",
    "        u_ph  = infer_phonetic(u_arr)\n",
    "        \n",
    "        if not ref_ap.exists(): return \"⚠️ No reference audio.\", \"\", u_ph, \"0%\"\n",
    "        \n",
    "        r_arr = load_processed(ref_ap)\n",
    "        r_ph  = infer_phonetic(r_arr)\n",
    "        \n",
    "        ratio = SequenceMatcher(None, r_ph, u_ph).ratio()\n",
    "        res = \"🟢 Excellent!\" if ratio > 0.85 else \"🟡 Good!\" if ratio > 0.65 else \"🟠 Keep practicing!\" if ratio > 0.4 else \"🔴 Significant difference.\"\n",
    "        return f\"{res}\\nScore: {ratio*100:.1f}%\", r_ph, u_ph, f\"{ratio*100:.1f}%\"\n",
    "    except Exception as e:\n",
    "        return f\"Error: {e}\", traceback.format_exc(), \"\", \"\"\n",
    "\n",
    "s_opts = [f\"{i:03d}. {get_name(i)} ({get_count(i)} ayahs)\" for i in range(1, 115)]\n",
    "\n",
    "with gr.Blocks(title='TasmiqAI', theme=gr.themes.Soft()) as demo:\n",
    "    gr.HTML(\"<div style='background:linear-gradient(135deg,#1a472a,#2d6a4f);color:white;padding:20px;border-radius:12px'>\"\n",
    "            \"<h1 style='margin:0'>📖 TasmiqAI — Recitation Expert</h1></div>\")\n",
    "    with gr.Row():\n",
    "        dd_s = gr.Dropdown(choices=s_opts, value=s_opts[0], label='📂 Surah', scale=3)\n",
    "        nb_a = gr.Number(value=1, minimum=1, label='📜 Ayah #', precision=0, scale=1)\n",
    "    with gr.Row():\n",
    "        with gr.Column(scale=3):\n",
    "            o_h = gr.Textbox(label='Target', interactive=False)\n",
    "            o_a = gr.Textbox(label='📝 Read This Ayah', interactive=False, lines=4)\n",
    "        with gr.Column(scale=2):\n",
    "            o_r = gr.Audio(label='🔊 Reference Audio', type='filepath', interactive=False)\n",
    "    o_m = gr.Markdown(\"⚡ Select a Surah/Ayah to begin.\")\n",
    "    mic_i = gr.Audio(sources=['microphone'], type='numpy', label='Record your recitation')\n",
    "    btn_c = gr.Button(\"✅ Check My Recitation\", variant='primary', size='lg')\n",
    "    o_res = gr.Textbox(label='🏆 Result', interactive=False)\n",
    "    with gr.Row():\n",
    "        o_rph = gr.Textbox(label='📌 Ref Phonetics', interactive=False)\n",
    "        o_uph = gr.Textbox(label='🎙️ Your Phonetics', interactive=False)\n",
    "    o_p = gr.Textbox(label='📈 Score', interactive=False)\n",
    "    \n",
    "    dd_s.change(auto_load_ayah, [dd_s, nb_a], [o_h, o_a, o_r, o_m])\n",
    "    nb_a.change(auto_load_ayah, [dd_s, nb_a], [o_h, o_a, o_r, o_m])\n",
    "    btn_c.click(run_check, [dd_s, nb_a, mic_i], [o_res, o_rph, o_uph, o_p])\n",
    "    demo.load(auto_load_ayah, [dd_s, nb_a], [o_h, o_a, o_r, o_m])\n",
    "\n",
    "demo.launch(share=False, inbrowser=True, debug=True)\n"
]

nb_data = {
    "cells": [
        md_cell(["# 📖 TasmiqAI — Quran Recitation Expert System\n"]),
        md_cell(["## Cell 1 — Install"]), code_cell(INSTALL_LINES),
        md_cell(["## Cell 2 — Expert System UI"]), code_cell(APP_LINES)
    ],
    "metadata": {"kernelspec": {"display_name": "Python (python-starter)", "language": "python", "name": "python-starter"}},
    "nbformat": 4, "nbformat_minor": 4
}

with open(NB_PATH, "w", encoding="utf-8") as f:
    json.dump(nb_data, f, indent=1)
print(f"Rebuilt successfully: {NB_PATH}")
